version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pi-hole-pi
    image: pihole/pihole:latest
    hostname: pi-hole-pi
    mac_address: d0:ca:ab:cd:ef:11
    cap_add: # Uncomment if you want to use Pi-Hole for DHCP
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'Europe/London'
      ServerIP: 192.168.170.254
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole:rw'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'    
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    networks:
      piunbound:
        ipv4_address: 192.168.170.254
    restart: unless-stopped

networks:
  piunbound:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.170.0/24
          gateway: 192.168.170.1
          ip_range: 192.168.170.252/30 # 192.168.1.3 and 192.168.1.4